name: Distribute Library

on:
   workflow_run:
     workflows: ["Unit test"]
     types: 
      - completed
   workflow_dispatch:
     
jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
        - name: Checkout yt-dlp-tver
          uses: actions/checkout@v4
          with:
            path: ./yt-dlp-tver

        - name: Checkout TVer
          uses: actions/checkout@v4
          with: 
            repository: kuriho/plugin.video.tver
            token: ${{ secrets.PAT }}
            path: ./tver

        - name: Copy over
          run: |
            cp -R ./yt-dlp-tver/lib/** ./tver/lib/
            
        - name: Get latest commit
          run: |
            echo "commit_upstream=$(git ls-remote https://github.com/yt-dlp/yt-dlp.git master | awk '{ print $1 }')" >> $GITHUB_ENV

        - name: Release
          run: |          
            cd ./tver
            git init
            git add -A 
            
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
            git commit -am "[CI] yt-dlp: ${{ env.commit_upstream }}"
            git push
