name: Update yt-dlp

on:
  schedule:
    - cron: '0 20 * * *'  # Customize the cron schedule as desired
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clone yt-dlp
        run: |
          git clone --depth 1 --branch master --no-checkout https://github.com/yt-dlp/yt-dlp.git /tmp/yt_dlp
          cd /tmp/yt_dlp
          git sparse-checkout set --no-cone
          git sparse-checkout add yt_dlp/* !yt_dlp/extractor/*
          git sparse-checkout add yt_dlp/extractor/brightcove.py yt_dlp/extractor/tver.py
          cd ..

      - name: Remove old files
        run: rm -r lib/yt_dlp

      - name: Move updated files
        run: mv /tmp/yt_dlp/yt_dlp lib/yt_dlp

      - name: Commit and push changes
        run: |
          git add lib/yt_dlp
          git commit -m "[CI] auto update yt-dlp to upstream commit"
          git push
