name: DummyDistribute Library

on:
   workflow_dispatch:
     
jobs:
   on-success:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Project A
          uses: actions/checkout@v2
          with:
            path: ./projectA

        - name: Checkout Project B
          uses: actions/checkout@master
          with: 
            repository: kuriho/target
            token: ${{ secrets.PAT }}
            path: ./projectB

        - name: Copy/Create file
          run: |
            cp -R ./projectA/lib/** ./projectB/lib/


        - name: Push Project B
          run: |
            cd ./projectB
            git init
            git add -A 
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "File Replicated from Project A"
            git push
         
