name: Unit test

on: 
  push:
    branches:
      - master
    paths:
      - 'lib/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'    
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --user requests pytest
      - name: Test with pytest
        run: |
          pytest test.py
