name: Unit test

on: 
  push:
    branches:
      - master
    paths:
      - 'lib/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'    
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --user requests pytest PySocks
      - name: Test with pytest
        env:
          GEO_VERIFICATION_PROXY: ${{ secrets.PROXY }} 
        run: |
          pytest test.py
