name: ytdlp
on:
  schedule:
    - cron:  '* 20 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: $GITHUB_WORKSPACE/.github/scripts/update.sh
      - run: git push
