name: TVer

on:
  schedule:
    - cron: '0 20 * * *'  # Customize the cron schedule as desired
  workflow_dispatch:

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Monorepo
        uses: dfdez/checkout@feat/sparse-checkout
        with:
          repository: yt-dlp/yt-dlp
          ref: master
          path: lib
          fetch-depth: 1
          sparse-checkout: |
            --no-cone
            yt_dlp/* 
            !yt_dlp/extractor/*

      - name: List Cloned Files
        run: |
          git init
          ls -R

      - name: Sparse Checkout
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set yt_dlp/* !yt_dlp/extractor/* --no-cone
          git sparse-checkout add yt_dlp/extractor/brightcove.py yt_dlp/extractor/tver.py --no-cone
        working-directory: lib
        
      - name: push changes to remote
        run: |
          git config --global user.name "user mane"
          git config --global user.email "user email"
          git add -A 
          git commit -m "commit message"
          git push
