name: ytdlp
on:
  schedule:
    - cron:  '* 20 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    -uses: dfdez/checkout@feat/sparse-checkout
      with:
        sparse-checkout: |
        .github
        src
