name: TVer

on:
  schedule:
    - cron: '0 20 * * *'  # Customize the cron schedule as desired
  workflow_dispatch:

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Monorepo
        uses: dfdez/checkout@feat/sparse-checkout
        with:
          repository: yt-dlp/yt-dlp
          ref: master
          path: yt_dlp
          fetch-depth: 1
          sparse-checkout: |
            --no-cone
            yt_dlp/* 
            !yt_dlp/extractor/*

      - name: List Cloned Files
        run: |
          ls yt_dlp/yt_dlp

      - name: Sparse Checkout
        run: |
          cd yt_dlp
          git sparse-checkout init --cone
          git sparse-checkout set yt_dlp/* !yt_dlp/extractor/* --no-cone
          git sparse-checkout add yt_dlp/extractor/brightcove.py yt_dlp/extractor/tver.py --no-cone
          cd ..

      - name: List Cloned Files 2
        run: |
          ls yt_dlp/yt_dlp/extractor

      - name: Copy Files
        run: |
          cp -r yt_dlp lib/yt_dlp

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update sparse checkout
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
